apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gz4ykbv3z-nodejs
  janus-idp.io/tekton: gz4ykbv3z-nodejs
  backstage.io/kubernetes-id: gz4ykbv3z-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gz4ykbv3z-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
