apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gz4ykbv3z-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gz4ykbv3z-nodejs 
  name: gz4ykbv3z-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: gz4ykbv3z-nodejs 
